import Link from 'next/link'
import { ArrowRight, CalendarClock, Check, Sparkles } from 'lucide-react'
import { PageShell, EmptyState } from '@/app/components/page-shell'
import { requireUser } from '@/lib/auth'
import { createIdea, generateContentKit, scheduleIdea } from './actions'

export default async function Studio({ searchParams }: { searchParams: Promise<{ error?: string; saved?: string; generated?: string; trend?: string }> }) {
  const { supabase, user } = await requireUser()
  const p = await searchParams
  const [{ data: ideas }, { data: trend }, { data: profile }] = await Promise.all([
    supabase.from('content_ideas').select('*').eq('user_id', user.id).order('created_at', { ascending: false }),
    p.trend ? supabase.from('trends').select('*').eq('id', p.trend).maybeSingle() : Promise.resolve({ data: null }),
    supabase.from('creator_profiles').select('niche,best_format,best_hook').eq('user_id', user.id).maybeSingle(),
  ])

  return <PageShell title="Content Studio" description="Turn a verified opportunity into something you can actually record, save and schedule.">
    {p.error && <div className="mb-6 border border-[#ff3d55]/20 bg-[#ff3d55]/5 p-4 text-xs text-[#ff3d55]">{p.error}</div>}
    {p.generated && <div className="mb-6 flex items-center gap-2 border-y border-black/10 py-4 text-xs font-semibold"><Check size={14} className="text-[#19a865" /> Content kit created and saved to your workspace.</div>}
    {p.saved && <div className="mb-6 flex items-center gap-2 border-y border-black/10 py-4 text-xs font-semibold"><Check size={14} className="text-[#19a865]" /> Draft saved.</div>}
    {trend ? <section className="border-y border-black/10 bg-[#111113] text-white"><div className="grid gap-0 lg:grid-cols-[1.05fr_.95fr]"><div className="p-7 sm:p-9 lg:p-12"><p className="eyebrow text-[#ff6b7e]">SELECTED OPPORTUNITY</p><h2 className="mt-5 max-w-2xl font-display text-5xl font-semibold leading-[.88] tracking-[-.05em]">{trend.title}</h2><p className="mt-5 max-w-xl text-sm leading-6 text-white/45">{trend.category || 'Creator signal'} · {Number(trend.score || 0)}/100 opportunity score · {trend.competition || 'Unknown'} competition.</p><form action={generateContentKit} className="mt-8"><input type="hidden" name="trend_id" value={trend.id} /><button className="inline-flex items-center gap-2 bg-[#ff3d55] px-5 py-3 text-xs font-bold transition hover:bg-white hover:text-black"><Sparkles size={14} /> Build content kit <ArrowRight size={14} /></button></form></div><div className="border-t border-white/10 p-7 sm:p-9 lg:border-l lg:border-t-0 lg:p-12"><p className="font-mono text-[8px] uppercase tracking-[.18em] text-white/30">Why VYRAL picked it</p><div className="mt-6 space-y-4 text-sm text-white/65"><p><span className="text-white/30">Fit</span><br />{Number(trend.niche_fit || 0)}/100 against your current creator profile.</p><p><span className="text-white/30">Your format</span><br />{profile?.best_format || 'Not enough history yet.'}</p><p><span className="text-white/30">Your strongest hook</span><br />{profile?.best_hook || 'Not enough history yet.'}</p></div></div></div></section> : <section className="mb-10 border-y border-black/10 py-8"><p className="eyebrow text-[#ff3d55]">START WITH A SIGNAL</p><h2 className="mt-3 font-display text-4xl font-semibold">Choose an opportunity before you make the video.</h2><p className="mt-3 max-w-xl text-sm leading-6 text-black/45">VYRAL will not invent a trend just to fill this page. Open Trend Radar and choose something backed by your available data.</p><Link href="/trends" className="mt-5 inline-flex items-center gap-2 text-xs font-bold">Open Trend Radar <ArrowRight size={14} /></Link></section>}
    <section className="mt-10 grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow">MANUAL DRAFT</p><h2 className="mt-2 font-display text-4xl font-semibold">Have your own idea?</h2><p className="mt-3 text-xs leading-5 text-black/40">Keep it here. The workspace stays yours even when there is no verified trend to follow.</p></div><form action={createIdea} className="border-t border-black/10 pt-5 space-y-4">{p.trend && <input type="hidden" name="trend_id" value={p.trend} />}<input className="field" name="title" required placeholder="Content title"/><input className="field" name="hook" required placeholder="Opening hook"/><textarea className="field min-h-32" name="script" placeholder="Script / talking points"/><textarea className="field min-h-24" name="caption" placeholder="Caption"/><input className="field" name="hashtags" placeholder="#hashtags separated by spaces"/><button className="inline-flex items-center gap-2 bg-black px-5 py-3 text-xs font-bold text-white transition hover:bg-[#ff3d55]">Save draft <Check size={14}/></button></form></section>
    <section className="mt-16"><div className="border-b border-black/10 pb-4"><p className="eyebrow">YOUR WORK</p><h2 className="mt-2 font-display text-4xl font-semibold">Saved content</h2></div>{ideas?.length ? <div className="divide-y divide-black/10">{ideas.map(i => <article key={i.id} className="grid gap-5 py-7 lg:grid-cols-[1fr_1.4fr_auto] lg:items-start"><div><p className="font-mono text-[8px] uppercase tracking-[.15em] text-black/25">{new Date(i.created_at).toLocaleDateString()}</p><h3 className="mt-2 font-display text-3xl font-semibold leading-none">{i.title}</h3><p className="mt-3 text-xs font-semibold text-[#ff3d55]">{i.hook}</p></div><div className="text-xs leading-6 text-black/55">{i.script || 'No script saved yet.'}<div className="mt-3 text-[10px] text-black/30">{(i.hashtags || []).map((h: string) => `#${h}`).join(' ')}</div></div><details className="group"><summary className="flex cursor-pointer list-none items-center gap-2 text-[10px] font-bold">Schedule <CalendarClock size={14}/></summary><form action={scheduleIdea} className="mt-4 flex flex-col gap-2 sm:flex-row"><input type="hidden" name="content_idea_id" value={i.id}/><input className="field" type="datetime-local" name="scheduled_for" required/><button className="bg-black px-4 py-3 text-[10px] font-bold text-white">Queue</button></form></details></article>)}</div> : <EmptyState title="Your studio is empty" description="Choose a verified opportunity or save your own idea. VYRAL will not manufacture content just to make this page look busy." href="/trends" action="Find an opportunity"/>}</section>
  </PageShell>
}
