import Link from 'next/link'
import { CalendarDays, Flame, LayoutDashboard, Activity, Users, Sparkles, Settings, LogOut, Zap } from 'lucide-react'
import { signOut } from '@/app/auth/actions'

const items = [['/','Overview',LayoutDashboard],['/trends','Trend Radar',Flame],['/studio','Content Studio',Sparkles],['/analytics','Analytics',Activity],['/competitors','Competitors',Users],['/calendar','Calendar',CalendarDays]] as const
export function PageShell({ children, title, description }: { children: React.ReactNode; title: string; description: string }) {
 return <main className="min-h-screen grid-bg"><aside className="fixed inset-y-0 left-0 hidden w-64 border-r border-white/5 bg-[#090a0e]/95 px-4 py-5 lg:block"><div className="flex items-center gap-3 px-3 mb-8"><div className="grid h-9 w-9 place-items-center rounded-xl bg-rose-500 shadow-glow"><Zap size={19} fill="white"/></div><span className="font-display text-xl font-bold">VYRAL</span></div><p className="px-3 mb-3 text-[10px] font-bold tracking-[.2em] text-zinc-600">WORKSPACE</p><nav className="space-y-1">{items.map(([href,label,Icon])=><Link key={href} href={href} className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm text-zinc-500 transition hover:bg-white/5 hover:text-white"><Icon size={17}/>{label}</Link>)}</nav><div className="absolute bottom-5 left-4 right-4 space-y-1"><Link href="/settings" className="flex w-full items-center gap-3 px-3 py-2 text-sm text-zinc-500 hover:text-white"><Settings size={16}/>Settings</Link><form action={signOut}><button className="flex w-full items-center gap-3 px-3 py-2 text-sm text-zinc-500 hover:text-white"><LogOut size={16}/>Sign out</button></form></div></aside><section className="lg:ml-64"><header className="sticky top-0 z-20 h-16 border-b border-white/5 bg-[#07080b]/85 px-5 backdrop-blur-xl lg:px-8 flex items-center justify-between"><Link href="/" className="font-display font-bold lg:hidden">VYRAL</Link><div className="hidden lg:block text-xs text-zinc-600">Creator workspace</div><Link href="/settings" className="text-zinc-500 hover:text-white"><Settings size={18}/></Link></header><div className="mx-auto max-w-[1500px] p-5 lg:p-8"><div className="mb-8"><p className="mb-2 text-[11px] font-bold tracking-[.2em] text-rose-400">VYRAL WORKSPACE</p><h1 className="font-display text-3xl font-bold tracking-tight">{title}</h1><p className="mt-2 text-sm text-zinc-500">{description}</p></div>{children}</div></section></main>
}
export function EmptyState({ title, description, href, action }: { title: string; description: string; href?: string; action?: string }) { return <div className="glass rounded-2xl p-10 text-center"><div className="mx-auto mb-4 grid h-12 w-12 place-items-center rounded-2xl bg-white/5"><Zap size={20} className="text-zinc-400"/></div><h2 className="font-display text-xl font-bold">{title}</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-zinc-500">{description}</p>{href && <Link href={href} className="mt-6 inline-flex rounded-xl bg-rose-500 px-4 py-2.5 text-sm font-bold hover:bg-rose-400">{action || 'Continue'}</Link>}</div> }
