import Link from 'next/link'
import { ArrowUpRight, Flame, Radar, Sparkles } from 'lucide-react'
import { PageShell } from '@/app/components/page-shell'

const trends=[
 {title:'3-second proof hook',category:'Education',score:94,velocity:94,fit:91,competition:'Medium',status:'Rising fast',window:'Next 24h'},
 {title:'Show me, then explain it',category:'How-to',score:89,velocity:87,fit:88,competition:'Low',status:'Early signal',window:'Next 48h'},
 {title:'One mistake I would never make again',category:'Storytelling',score:84,velocity:82,fit:85,competition:'Medium',status:'Rising',window:'Next 72h'},
 {title:'POV: I wish I knew this sooner',category:'Creator',score:81,velocity:76,fit:89,competition:'Low',status:'Watch',window:'This week'},
 {title:'Before / after in 7 seconds',category:'Transformation',score:78,velocity:73,fit:84,competition:'Medium',status:'Watch',window:'This week'},
 {title:'The unpopular truth about...',category:'Opinion',score:74,velocity:68,fit:82,competition:'High',status:'Competitive',window:'Monitor'},
]
export default function Trends(){return <PageShell title="Opportunities" description="VYRAL scans signals, creator behavior and your Creator DNA to surface opportunities worth testing. Scores are directional—not promises of virality.">
 <div className="grid gap-4 md:grid-cols-3"><Stat icon={Radar} label="Signals monitored" value="1,284"/><Stat icon={Flame} label="Rising opportunities" value="27"/><Stat icon={Sparkles} label="Best fit for you" value="91/100"/></div>
 <div className="mt-10 flex items-end justify-between"><div><p className="eyebrow text-[#ff3d55]">LIVE RADAR</p><h2 className="mt-2 font-display text-4xl font-semibold">What is moving now</h2></div><span className="rounded-full bg-white px-3 py-2 text-[10px] font-bold text-black/45">Updated moments ago</span></div>
 <div className="mt-5 grid gap-4 lg:grid-cols-2 xl:grid-cols-3">{trends.map((t,i)=><article key={t.title} className="group rounded-[26px] border border-black/[.08] bg-white p-6 shadow-[0_10px_30px_rgba(17,17,19,.035)] interactive"><div className="flex items-center justify-between"><span className="rounded-full bg-[#ff3d55]/10 px-2.5 py-1 text-[9px] font-bold uppercase tracking-[.12em] text-[#ff3d55]">{t.status}</span><span className="font-mono text-[10px] text-black/25">0{i+1}</span></div><h3 className="mt-7 font-display text-3xl font-semibold leading-tight">{t.title}</h3><p className="mt-2 text-[11px] text-black/35">{t.category} · creator signal</p><div className="mt-7 flex items-end justify-between"><div><span className="text-[9px] font-bold uppercase tracking-wider text-black/30">Opportunity</span><p className="font-display text-5xl font-semibold">{t.score}<small className="ml-1 text-base text-black/25">/100</small></p></div><div className="grid h-16 w-16 place-items-center rounded-full border-[7px] border-[#f0f0ec] border-t-[#ff3d55] text-[9px] font-bold">{t.fit}% fit</div></div><div className="mt-6 grid grid-cols-3 gap-3 border-t border-black/[.07] pt-4"><Metric label="Velocity" value={`${t.velocity}%`}/><Metric label="Fit" value={`${t.fit}%`}/><Metric label="Competition" value={t.competition}/></div><div className="mt-5 flex items-center justify-between"><span className="text-[10px] font-semibold text-black/35">Best window: {t.window}</span><Link href={`/studio?trend=${i+1}`} className="grid h-9 w-9 place-items-center rounded-full bg-black text-white transition group-hover:bg-[#ff3d55]"><ArrowUpRight size={14}/></Link></div></article>)}</div>
 </PageShell>}
function Stat({icon:Icon,label,value}:{icon:any;label:string;value:string}){return <div className="rounded-[22px] border border-black/[.08] bg-white p-5 shadow-[0_10px_30px_rgba(17,17,19,.03)] interactive"><Icon size={17} className="text-[#ff3d55]"/><p className="mt-5 text-[9px] font-bold uppercase tracking-[.16em] text-black/30">{label}</p><p className="mt-1 font-display text-3xl font-semibold">{value}</p></div>}
function Metric({label,value}:{label:string;value:string}){return <div><p className="text-[8px] font-bold uppercase tracking-wider text-black/30">{label}</p><p className="mt-1 text-[11px] font-bold">{value}</p></div>}
