'use client';

import { useState } from 'react';
import { Activity, ArrowUpRight, Bell, CalendarDays, ChevronRight, Flame, Hash, LayoutDashboard, Lightbulb, Menu, Play, Search, Settings, Sparkles, Target, TrendingUp, Users, Zap } from 'lucide-react';

const trends = [
  { title: '3 mistakes nobody tells you about…', category: 'Format', score: 94, delta: '+18%', color: 'bg-rose-500', tag: 'RISING' },
  { title: 'POV: You finally understand it', category: 'Hook', score: 91, delta: '+24%', color: 'bg-amber-400', tag: 'BREAKOUT' },
  { title: 'Before / after reveal', category: 'Visual', score: 87, delta: '+11%', color: 'bg-violet-400', tag: 'RISING' },
];
const nav = [
  ['Overview', LayoutDashboard], ['Trend Radar', Flame], ['Content Studio', Sparkles], ['Analytics', Activity], ['Competitors', Users], ['Calendar', CalendarDays],
];

export default function Home() {
  const [active, setActive] = useState('Overview');
  const [menu, setMenu] = useState(false);
  return <main className="min-h-screen grid-bg">
    <aside className="fixed inset-y-0 left-0 hidden w-64 border-r border-white/5 bg-[#090a0e]/95 px-4 py-5 lg:block">
      <div className="flex items-center gap-3 px-3 mb-8"><div className="grid h-9 w-9 place-items-center rounded-xl bg-rose-500 shadow-glow"><Zap size={19} fill="white" /></div><span className="font-display text-xl font-bold tracking-tight">VYRAL</span></div>
      <p className="px-3 mb-3 text-[10px] font-bold tracking-[.2em] text-zinc-600">WORKSPACE</p>
      <nav className="space-y-1">{nav.map(([label,Icon])=><button key={label as string} onClick={()=>setActive(label as string)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm transition ${active===label?'bg-white/8 text-white':'text-zinc-500 hover:bg-white/5 hover:text-zinc-200'}`}><Icon size={17}/><span>{label as string}</span>{label==='Trend Radar'&&<span className="ml-auto h-2 w-2 rounded-full bg-rose-500"/>}</button>)}</nav>
      <div className="absolute bottom-5 left-4 right-4"><div className="rounded-2xl border border-white/8 bg-gradient-to-br from-white/[.07] to-white/[.02] p-4"><div className="mb-2 flex items-center gap-2 text-xs font-semibold"><Target size={14} className="text-rose-400"/> Creator score</div><div className="flex items-end justify-between"><strong className="font-display text-3xl">82</strong><span className="text-xs text-emerald-400">+7 this week</span></div><div className="mt-3 h-1.5 rounded-full bg-white/8"><div className="h-full w-[82%] rounded-full bg-rose-500"/></div></div><button className="mt-3 flex w-full items-center gap-3 px-3 py-2 text-sm text-zinc-500"><Settings size={16}/> Settings</button></div>
    </aside>

    <section className="lg:ml-64">
      <header className="sticky top-0 z-20 flex h-16 items-center justify-between border-b border-white/5 bg-[#07080b]/85 px-5 backdrop-blur-xl lg:px-8"><div className="flex items-center gap-3"><button className="lg:hidden text-zinc-400" onClick={()=>setMenu(!menu)}><Menu/></button><div className="lg:hidden font-display font-bold">VYRAL</div><div className="hidden md:flex items-center gap-2 rounded-xl border border-white/7 bg-white/[.025] px-3 py-2 text-xs text-zinc-500"><Search size={15}/> Search anything… <span className="ml-12 rounded bg-white/5 px-1.5 py-0.5 text-[10px]">⌘ K</span></div></div><div className="flex items-center gap-4"><button className="relative text-zinc-400"><Bell size={19}/><span className="absolute -right-1 -top-1 h-2 w-2 rounded-full bg-rose-500"/></button><div className="flex items-center gap-2 border-l border-white/7 pl-4"><div className="grid h-8 w-8 place-items-center rounded-full bg-gradient-to-br from-rose-400 to-violet-600 text-xs font-bold">MA</div><span className="hidden text-sm md:block">Creator</span></div></div></header>
      {menu&&<div className="border-b border-white/5 bg-[#0d0f14] p-3 lg:hidden">{nav.map(([label,Icon])=><button key={label as string} onClick={()=>{setActive(label as string);setMenu(false)}} className="flex w-full gap-3 rounded-lg p-3 text-left text-sm text-zinc-300"><Icon size={17}/>{label as string}</button>)}</div>}
      <div className="mx-auto max-w-[1500px] p-5 lg:p-8">
        <div className="mb-8 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><div className="mb-2 flex items-center gap-2 text-xs font-semibold text-emerald-400"><span className="h-1.5 w-1.5 rounded-full bg-emerald-400"/> LIVE INTELLIGENCE</div><h1 className="font-display text-3xl font-bold tracking-tight lg:text-4xl">Good evening, creator.</h1><p className="mt-2 text-sm text-zinc-500">Here are the opportunities most likely to move your account forward today.</p></div><button className="flex w-fit items-center gap-2 rounded-xl bg-rose-500 px-4 py-2.5 text-sm font-semibold shadow-glow transition hover:bg-rose-400"><Sparkles size={16}/> Create with VYRAL</button></div>

        <div className="grid gap-4 md:grid-cols-3"><Stat icon={Flame} label="Opportunity score" value="94" sub="Your best opportunity today" trend="+12%"/><Stat icon={TrendingUp} label="Momentum" value="8.4×" sub="Above your baseline" trend="+31%"/><Stat icon={Play} label="Next best post" value="6:42 PM" sub="Optimal window today" trend="91% fit"/></div>

        <div className="mt-5 grid gap-5 xl:grid-cols-[1.55fr_1fr]">
          <div className="glass rounded-2xl p-5 lg:p-6"><div className="mb-6 flex items-start justify-between"><div><p className="text-[11px] font-bold tracking-[.18em] text-zinc-600">TOP OPPORTUNITY</p><h2 className="mt-2 font-display text-xl font-bold">Ride the “3 mistakes” wave</h2></div><span className="rounded-full bg-rose-500/10 px-3 py-1 text-[10px] font-bold tracking-wider text-rose-300">94 / 100</span></div><div className="rounded-2xl border border-rose-500/15 bg-rose-500/[.035] p-5"><div className="flex flex-wrap items-center gap-2"><span className="rounded-md bg-rose-500/15 px-2 py-1 text-[10px] font-bold text-rose-300">RISING FAST</span><span className="text-xs text-zinc-500">Format · Business niche</span></div><p className="mt-4 text-lg font-semibold">“3 mistakes that are quietly killing your business…”</p><div className="mt-5 grid grid-cols-2 gap-4 text-xs sm:grid-cols-4"><Metric k="Velocity" v="+218%"/><Metric k="Niche fit" v="96%"/><Metric k="Competition" v="Low"/><Metric k="Window" v="4–9 days"/></div><button className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-white py-3 text-sm font-bold text-black hover:bg-zinc-200">Build content kit <ArrowUpRight size={16}/></button></div></div>
          <div className="glass rounded-2xl p-5 lg:p-6"><div className="mb-5 flex items-center justify-between"><div><p className="text-[11px] font-bold tracking-[.18em] text-zinc-600">CREATOR DNA</p><h2 className="mt-2 font-display text-xl font-bold">What works for you</h2></div><span className="text-xs text-zinc-500">Updated today</span></div><div className="space-y-4"><DNA label="Best format" value="Talking head" pct={92}/><DNA label="Best hook" value="Contrarian" pct={89}/><DNA label="Sweet spot" value="22–31 sec" pct={94}/><DNA label="Top pillar" value="Business mistakes" pct={87}/></div></div>
        </div>

        <div className="mt-5 glass rounded-2xl p-5 lg:p-6"><div className="mb-6 flex items-end justify-between"><div><p className="text-[11px] font-bold tracking-[.18em] text-zinc-600">TREND RADAR</p><h2 className="mt-2 font-display text-xl font-bold">Trends moving before the crowd</h2></div><button className="flex items-center gap-1 text-xs font-semibold text-zinc-400 hover:text-white">Open radar <ChevronRight size={14}/></button></div><div className="grid gap-3 md:grid-cols-3">{trends.map(t=><div key={t.title} className="group rounded-xl border border-white/6 bg-white/[.02] p-4 transition hover:border-white/12 hover:bg-white/[.04]"><div className="flex items-center justify-between"><span className={`rounded px-2 py-1 text-[9px] font-bold tracking-wider text-black ${t.color}`}>{t.tag}</span><span className="text-xs font-bold text-emerald-400">{t.delta}</span></div><h3 className="mt-4 min-h-12 text-sm font-semibold leading-5">{t.title}</h3><div className="mt-4 flex items-center justify-between text-xs"><span className="text-zinc-600">{t.category}</span><span className="font-bold">{t.score}<span className="text-zinc-600">/100</span></span></div><div className="mt-2 h-1 rounded-full bg-white/7"><div className="h-full rounded-full bg-white" style={{width:`${t.score}%`}}/></div></div>)}</div></div>

        <div className="mt-5 grid gap-5 lg:grid-cols-2"><div className="glass rounded-2xl p-5"><div className="flex items-center justify-between"><div><p className="text-[11px] font-bold tracking-[.18em] text-zinc-600">NEXT ACTION</p><h2 className="mt-2 font-display text-lg font-bold">Your posting plan</h2></div><CalendarDays size={18} className="text-zinc-600"/></div><div className="mt-5 flex items-center gap-4 rounded-xl bg-white/[.025] p-4"><div className="grid h-11 w-11 place-items-center rounded-xl bg-rose-500/10 text-rose-400"><Zap size={19}/></div><div className="flex-1"><p className="text-sm font-semibold">Publish “3 mistakes” video</p><p className="mt-1 text-xs text-zinc-600">Today · 6:42–7:18 PM · 91% fit</p></div><button className="rounded-lg border border-white/8 px-3 py-2 text-xs font-semibold">Prepare</button></div></div><div className="glass rounded-2xl p-5"><div><p className="text-[11px] font-bold tracking-[.18em] text-zinc-600">RECENT DIAGNOSIS</p><h2 className="mt-2 font-display text-lg font-bold">Your last post</h2></div><div className="mt-5 flex items-center gap-4"><div className="grid h-11 w-11 place-items-center rounded-xl bg-amber-400/10 text-amber-400"><Lightbulb size={19}/></div><div><p className="text-sm font-semibold">Strong topic. Slow payoff.</p><p className="mt-1 text-xs text-zinc-600">34% drop between 3–6 seconds</p></div></div><div className="mt-4 rounded-lg bg-white/[.025] p-3 text-xs text-zinc-500">Next experiment: <b className="text-zinc-300">move the payoff into the first 2 seconds.</b></div></div></div>
      </div>
    </section>
  </main>
}
function Stat({icon:Icon,label,value,sub,trend}:{icon:any,label:string,value:string,sub:string,trend:string}){return <div className="glass rounded-2xl p-5"><div className="flex items-start justify-between"><span className="grid h-9 w-9 place-items-center rounded-xl bg-white/[.04] text-zinc-300"><Icon size={17}/></span><span className="text-[10px] font-bold text-emerald-400">{trend}</span></div><p className="mt-5 text-xs text-zinc-600">{label}</p><p className="mt-1 font-display text-2xl font-bold">{value}</p><p className="mt-1 text-xs text-zinc-500">{sub}</p></div>}
function Metric({k,v}:{k:string,v:string}){return <div><p className="text-zinc-600">{k}</p><p className="mt-1 font-semibold text-zinc-200">{v}</p></div>}
function DNA({label,value,pct}:{label:string,value:string,pct:number}){return <div><div className="mb-2 flex justify-between text-xs"><span className="text-zinc-500">{label}</span><span className="font-semibold text-zinc-200">{value}</span></div><div className="h-1 rounded-full bg-white/7"><div className="h-full rounded-full bg-zinc-300" style={{width:`${pct}%`}}/></div></div>}
