import Link from 'next/link'
import { ArrowUpRight, Flame, Play, TrendingUp, Sparkles, Clock3, Stethoscope, ChevronRight } from 'lucide-react'
import { PageShell } from '@/app/components/page-shell'

const opportunities = [
  { id:'trend-1', tag:'RISING FAST', title:'The 3-second proof hook', description:'Show the result before the explanation. Your niche is under-supplied on this format.', velocity:94, fit:91, competition:'Medium', eta:'Best within 24h' },
  { id:'trend-2', tag:'EARLY SIGNAL', title:'Show me, then explain it', description:'A visual-first teaching format is gaining momentum with low creator competition.', velocity:87, fit:88, competition:'Low', eta:'Best within 48h' },
  { id:'trend-3', tag:'RISING', title:'One mistake I would never make again', description:'Confessional storytelling is creating unusually strong comment activity.', velocity:82, fit:85, competition:'Medium', eta:'Best within 72h' },
]
const videos = [
  { title:'Why I stopped doing this', views:'184.2K', completion:71, delta:'+28%', status:'Strong' },
  { title:'3 things nobody tells you', views:'93.6K', completion:64, delta:'+11%', status:'Healthy' },
  { title:'My biggest mistake', views:'41.2K', completion:58, delta:'-6%', status:'Needs work' },
]

export default function Home(){
  return <PageShell title="Good to see you, Mahir." description="Know what is moving, decide what to make, and turn your next idea into a stronger TikTok. VYRAL brings your growth system into one place.">
    <div className="mb-7 flex flex-wrap items-center justify-between gap-4 rounded-[22px] border border-black/[.08] bg-white p-4 shadow-[0_12px_35px_rgba(17,17,19,.04)] interactive">
      <div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-[#ff3d55]/10 text-[#ff3d55]"><Sparkles size={17}/></div><div><p className="text-xs font-bold">Demo intelligence is active</p><p className="mt-0.5 text-[11px] text-black/40">Sample signals are being used until TikTok integrations are connected.</p></div></div>
      <span className="rounded-full border border-black/[.08] bg-[#f6f6f2] px-3 py-1.5 text-[9px] font-bold uppercase tracking-[.16em] text-black/45 shimmer">Demo mode</span>
    </div>

    <section className="grid gap-4 xl:grid-cols-[1.4fr_.6fr]">
      <div className="relative min-h-[360px] overflow-hidden rounded-[30px] bg-[#111113] p-7 text-white shadow-[0_28px_70px_rgba(17,17,19,.15)] lg:p-10 interactive">
        <div className="absolute -right-24 -top-24 h-72 w-72 rounded-full bg-[#ff3d55]/20 blur-3xl"/><div className="absolute bottom-0 left-1/3 h-40 w-40 rounded-full bg-[#315cff]/10 blur-3xl"/>
        <div className="scan-line"/><div className="relative flex h-full flex-col justify-between"><div><div className="flex items-center gap-2 text-[9px] font-bold uppercase tracking-[.2em] text-[#ff6b7e]"><span className="h-1.5 w-1.5 rounded-full bg-[#ff3d55] pulse-dot"/> Your next move</div><h2 className="mt-5 max-w-3xl font-display text-5xl font-semibold leading-[.95] tracking-[-.025em] lg:text-7xl">Turn the <em className="text-[#ff6b7e]">3-second proof hook</em> into your next video.</h2><p className="mt-5 max-w-xl text-sm leading-6 text-white/55">The strongest combination of momentum, niche fit and manageable competition in your current radar.</p></div><div className="mt-8 flex flex-wrap gap-3"><Link href="/studio?trend=trend-1" className="inline-flex items-center gap-2 rounded-full bg-white px-5 py-3 text-xs font-bold text-black transition hover:scale-[1.02]">Build this video <ArrowUpRight size={14}/></Link><Link href="/trends" className="inline-flex items-center gap-2 rounded-full border border-white/15 px-5 py-3 text-xs font-semibold text-white/70 hover:bg-white/10">Explore opportunities</Link></div></div>
      </div>
      <div className="rounded-[30px] border border-black/[.08] bg-white p-6 shadow-[0_12px_35px_rgba(17,17,19,.04)] interactive"><div className="flex items-center justify-between"><div><p className="text-[9px] font-bold uppercase tracking-[.2em] text-black/35">Growth pulse</p><p className="mt-2 font-display text-5xl font-semibold">+28%</p><p className="mt-1 text-[10px] text-black/35">vs. previous 12 posts</p></div><div className="grid h-11 w-11 place-items-center rounded-2xl bg-[#19a865]/10 text-[#19a865]"><TrendingUp size={18}/></div></div><div className="mt-10 flex h-28 items-end gap-1.5">{[28,35,32,48,44,57,51,68,64,78,73,92].map((h,i)=><span key={i} className="flex-1 rounded-t bg-[#111113] transition-all duration-500 hover:bg-[#ff3d55]" style={{height:`${h}%`}}/> )}</div><div className="mt-3 flex justify-between text-[10px] text-black/35"><span>Last 12 posts</span><span>Views momentum</span></div></div>
    </section>

    <section className="mt-12"><div className="mb-5 flex items-end justify-between"><div><p className="text-[9px] font-bold uppercase tracking-[.2em] text-[#ff3d55]">01 / OPPORTUNITIES</p><h2 className="mt-1 font-display text-4xl font-semibold tracking-tight">Worth acting on</h2></div><Link href="/trends" className="text-[11px] font-semibold text-black/40 hover:text-black">View radar →</Link></div>
      <div className="grid gap-4 lg:grid-cols-3">{opportunities.map((o,i)=><Link href={`/studio?trend=${o.id}`} key={o.id} className="group rounded-[24px] border border-black/[.08] bg-white p-5 shadow-[0_10px_30px_rgba(17,17,19,.035)] interactive"><div className="flex items-center justify-between"><span className="text-[9px] font-bold tracking-[.16em] text-[#ff3d55]">{o.tag}</span><span className="font-mono text-[9px] text-black/25">0{i+1}</span></div><h3 className="mt-8 font-display text-3xl font-semibold leading-tight">{o.title}</h3><p className="mt-3 text-xs leading-5 text-black/45">{o.description}</p><div className="mt-7 grid grid-cols-3 gap-2 border-t border-black/[.07] pt-4"><Metric label="Velocity" value={`${o.velocity}%`}/><Metric label="Niche fit" value={`${o.fit}%`}/><Metric label="Competition" value={o.competition}/></div><div className="mt-5 flex items-center justify-between text-[10px] font-semibold text-black/35"><span>{o.eta}</span><ChevronRight size={14} className="transition group-hover:translate-x-1 group-hover:text-[#ff3d55]"/></div></Link>)}</div>
    </section>

    <section className="mt-12 grid gap-4 xl:grid-cols-[1fr_360px]">
      <div className="rounded-[26px] border border-black/[.08] bg-white p-5 shadow-[0_10px_30px_rgba(17,17,19,.035)] lg:p-6"><div className="flex items-center justify-between"><div><p className="text-[9px] font-bold uppercase tracking-[.2em] text-black/35">02 / PERFORMANCE DOCTOR</p><h2 className="mt-1 font-display text-3xl font-semibold">Your recent videos</h2></div><Link href="/analytics" className="text-[11px] font-semibold text-black/40 hover:text-black">Open analytics →</Link></div><div className="mt-5 space-y-1">{videos.map(v=><div key={v.title} className="grid grid-cols-[1fr_auto] gap-4 rounded-2xl p-3 transition hover:bg-[#f6f6f2] md:grid-cols-[1fr_90px_100px_80px]"><div className="min-w-0"><div className="flex items-center gap-2"><Play size={12} className="text-[#ff3d55]"/><p className="truncate text-xs font-bold">{v.title}</p></div><p className="mt-1 text-[10px] text-black/35">{v.status} performance</p></div><div className="hidden md:block"><p className="text-xs font-bold">{v.views}</p><p className="text-[9px] text-black/30">views</p></div><div className="hidden md:block"><p className="text-xs font-bold">{v.completion}%</p><p className="text-[9px] text-black/30">completion</p></div><span className={`self-center text-[10px] font-bold ${v.delta.startsWith('+')?'text-[#19a865]':'text-[#ff3d55]'}`}>{v.delta}</span></div>)}</div></div>
      <div className="rounded-[26px] bg-[#ff3d55] p-6 text-white shadow-[0_20px_50px_rgba(255,61,85,.16)] interactive"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-white/15"><Stethoscope size={18}/></div><p className="mt-5 text-[9px] font-bold uppercase tracking-[.2em] text-white/60">AI diagnosis</p><h3 className="mt-2 font-display text-3xl font-semibold leading-tight">Your hook is the bottleneck.</h3><p className="mt-3 text-xs leading-5 text-white/75">Your strongest videos retain attention early. The weakest drops happen before the first 2 seconds.</p><Link href="/studio" className="mt-5 inline-flex items-center gap-2 rounded-full bg-white px-4 py-2.5 text-[11px] font-bold text-black">Open Hook Lab <ArrowUpRight size={13}/></Link></div>
    </section>

    <section className="mt-12 grid gap-4 sm:grid-cols-3"><Quick icon={Flame} title="Find a signal" text="Scan emerging trends" href="/trends"/><Quick icon={Sparkles} title="Make a video" text="Generate your content kit" href="/studio"/><Quick icon={Clock3} title="Plan your week" text="Find the best windows" href="/calendar"/></section>
  </PageShell>
}
function Metric({label,value}:{label:string;value:string}){return <div><p className="text-[8px] font-bold uppercase tracking-wider text-black/30">{label}</p><p className="mt-1 text-[11px] font-bold text-black/75">{value}</p></div>}
function Quick({icon:Icon,title,text,href}:{icon:any;title:string;text:string;href:string}){return <Link href={href} className="group rounded-[22px] border border-black/[.08] bg-white p-5 shadow-[0_10px_30px_rgba(17,17,19,.035)] interactive"><Icon size={17} className="text-[#ff3d55]"/><div className="mt-7 flex items-center justify-between"><div><p className="text-xs font-bold">{title}</p><p className="mt-1 text-[10px] text-black/35">{text}</p></div><ArrowUpRight size={14} className="text-black/25 transition group-hover:-translate-y-0.5 group-hover:translate-x-0.5 group-hover:text-black"/></div></Link>}
